config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :posts do
    member do
     get :toggle_status
    end
  end
  resources :portfolios, except: [ :show ]

  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show"

  get "about-me", to: "pages#about"
  get "contact",  to: "pages#contact"
  resources :guides

  root to: "pages#home"

  get "comments", to: "comments#info"

  get "comments/show", to: "comments#show"
  resources :user

  get "users", to: "users#index"

  resources :teachers do
    resources :courses
  end

  resources :students do
    resources :enrollments
  end

  resources :courses do
    resources :feedbacks
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  #
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :poly_comments, as: :commentable
  belongs_to :user
  # around_update :log_updating
  after_save -> { Rails.logger.info("You have created an object!") }
  after_commit -> { Rails.logger.info("You have created an object! by commit callback") }

  # after_initialize do |user|
  #   Rails.logger.info("You have initialized an object!")
  # end

  # after_find do |user|
  #   Rails.logger.info("You have found an object!")
  # end
  accepts_nested_attributes_for :comments
  # around_update -> { Rails.logger.info("Congratulations, the callback has run!") }
  def log_updating
    Rails.logger.info("Updating user with email: #{title}")
    yield
    Rails.logger.info("User updated with email: #{title}")
  end
  enum :status, { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # check_authorization
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end
  before_action :set_post, only: %i[show edit update destroy toggle_status]

  # GET /posts or /posts.json
  def index
    # Using accessible_by to filter posts based on user permissions
    @posts = Post.accessible_by(current_ability)
    Rails.logger.info("current_ability: #{@posts.inspect}")
    # Use can? to check if the user can read any posts
    if can?(:read, Post)
      @posts = @posts.order(:title).page(params[:page]).per(5)
    else
      redirect_to root_path, alert: "You are not authorized to view posts."
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    # Using authorize! to ensure the user can read this specific post
    authorize! :create, @post
  end

  # GET /posts/new
  def new
    # Only site admins should be able to create new posts
    authorize! :create, Post
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    # Only site admins should be able to edit new posts
    authorize! :edit, @post
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)
    authorize! :create, @post  # Check if the user can create a post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    # Check if the user can update this specific post
    authorize! :update, @post

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    # Check if the user can destroy this specific post
    authorize! :destroy, @post

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    authorize! :update, @post  # Check if the user can update the post status

    if @post.draft?
      @post.published!
    elsif @post.published?
      @post.draft!
    end
    redirect_to posts_url, notice: "Post status has been updated."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, comments_attributes: [ :content ])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <h3>Comments</h3>
  <div id="comments">
    <%= form.fields_for :comments do |comment_form| %>
      <div class="comment-fields">
        <%= comment_form.label :content, "Comment", style: "display: block" %>
        <%= comment_form.text_area :content %>
      </div>
    <% end %>
  </div>
  <br>
  <button type="button" onclick="addCommentFields()">Add more comment</button>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<script>
  let commentIndex = 0;
  function addCommentFields() {
    var commentsDiv = document.getElementById('comments');
    var newCommentDiv = document.createElement('div');
    newCommentDiv.className = 'comment-fields';
    newCommentDiv.innerHTML = `
      <div>
        <label for="post_comments_attributes_${commentIndex}_content" style="display: block">Comment</label>
        <textarea name="post[comments_attributes][${commentIndex}][content]" id="post_comments_attributes_${commentIndex}_content"></textarea>
      </div>`;
    commentsDiv.appendChild(newCommentDiv);
    commentIndex++;
  }
</script>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>
<%= link_to "New post", new_post_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= render post %></td>
        <td><%= link_to post.status, toggle_status_post_path(post) %></td>
        <td>
          <% if can? :read, post %>
            <%= link_to "Show this post", post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<h3>Comments:</h3>
<% if @post.comments.any? %>
  <ul>
    <% @post.comments.each do |comment| %>
      <li><%= comment.content %></li>
    <% end %>
  </ul>
<% else %>
  <p>No comments available.</p>
<% end %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %>
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>